### ISSUE TITLE
'sql: Scan error on column index 8, name "organization"..' while accessing 'func UsersShow()'

### ISSUE THREAD

**Issue by vulcangz** [turnkey-commerce/helpgiving#1]
A good buffalo implementation gave me some ideas, thanks. 

There is a issue：when using mysql as the database, there is an error accessing 'func UsersShow': 

> mysql select one: sql: Scan error on column index 8, name "organization": unsupported Scan, storing driver.Value type []uint8 into type *models.Organization"
github.com/turnkey-commerce/helpgiving/actions.UsersShow
D:/working/golang/src/github.com/turnkey-commerce/helpgiving/actions/users.go:77
...

In func actions.UsersShow, the defined structure 'user' contains the same field name "organization" as the Association field name "Organization" in 'models.User', which may cause this error. After modifying one of them, UsersShow runs fine.

1. actions.UsersShow
https://github.com/turnkey-commerce/helpgiving/blob/1bb19d106acdf8be9b96920a0521e61aa9c30831/actions/users.go#L69-L78

Change the above as:
```Go
// Allocate an empty User
	user := &struct {
		models.User
		OrganizationName string `db:"organization_name"`
		Role         string
	}{}

	if err := tx.RawQuery("select users.*, organizations.name as organization_name from users, organizations where users.organization_id = organizations.id AND users.id = ?", c.Param("user_id")).First(user); err != nil {
		return errors.WithStack(err)
	}
```

2. models.User
https://github.com/turnkey-commerce/helpgiving/blob/1bb19d106acdf8be9b96920a0521e61aa9c30831/models/user.go#L30

3. view: users/show.html
https://github.com/turnkey-commerce/helpgiving/blob/1bb19d106acdf8be9b96920a0521e61aa9c30831/templates/users/show.html#L18

Change it as:

```Go
<strong>Organization</strong>: <%= user.OrganizationName %>
```
Not tested under sqlite3.

**Comment by turnkey-commerce** [comment]
Thanks @vulcangz! I haven't updated this one in a while, but will fix that when I get back to it.
